### ISSUE TITLE
无法读取链接列表

### ISSUE THREAD

**Issue by kenee** [junstor/memadmin#1]
服务器的php如果开启magic_quotes_gpc，提交的数据都会知道加斜杠的，这样会导致反序列化失败。我在
$res = unserialize($_COOKIE['memadmin_cookie_conlist']);
前加上这句话解决问题：
$_COOKIE['memadmin_cookie_conlist'] = stripslashes($_COOKIE['memadmin_cookie_conlist']);

**Comment by junstor** [comment]
已经修正了这个问题，多谢
