### ISSUE TITLE
nginx+fastcgi cache出现 405错误

### ISSUE THREAD

**Issue by ahu** [junstor/memadmin#2]
我发现在启用了fastcgi cache的nginx下登录不了，点击登录按钮出现405错误，如何解决？
起初我以为单纯是fastcgi cache的问题，后来发现别的php程序如phpmyadmin等均可以正常登录；我在网上找了一些nginx+405的相关解决方案，无效；包括给index.php或config.php添加不缓存header也不行。我在本地Windows上的没加fastcgi cache的nginx上倒是可以用。

**Comment by junstor** [comment]
于 2011/10/7 0:30, ahu 写道:

> 我发现在启用了fastcgi cache的nginx下登录不了，点击登录按钮出现405错误，如何解决？
> 起初我以为单纯是fastcgi cache的问题，后来发现别的php程序如phpmyadmin等均可以正常登录；我在网上找了一些nginx+405的相关解决方案，无效；包括给index.php或config.php添加不缓存header也不行。我在本地Windows上的没加fastcgi cache的nginx上倒是可以用。
> 
> 能否把配置文件发来看看。我刚试了一下开启fastcgi_cache可以登录，可能我们 
> 配置的不一样，登录界面确实没有像phpmyadmin 那样直接post，而都是ajax post 
> 过去的，所以可能问题出在这块。

**Comment by ahu** [comment]
请看一下这个帖子：
http://forum.nginx.org/read.php?2,39564,216317#msg-216317

**Comment by ahu** [comment]
我刚才按照ngx_cache_purge作者的指示升级到了ngx_cache_purge-1.4，奇怪的是不仅可以正常purge fastcgi cache了，而且memadmin也可以正常登录使用了！
